name: PHPUnit tests

on:
  push:
    branches:
      - github-actions

jobs:
  provide_php_versions_json:
    runs-on: ubuntu-latest

    steps:
      # git clone + use PHP + composer install
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0

      - uses: "ramsey/composer-install@v1"

      # to see the output
      - run: vendor/bin/easy-ci php-versions-json

      # here we create the json, we need the "id:" so we can use it in "outputs" below
      - id: output_data
        run: echo "::set-output name=matrix::$(vendor/bin/easy-ci php-versions-json)"

      # here, we save the result of this 1st phase to the "outputs"
    outputs:
      matrix: ${{ steps.output_data.outputs.matrix }}

  build-and-test:
    needs: provide_php_versions_json
    strategy:
      fail-fast: false
      matrix:
        php: ${{ fromJson(needs.provide_php_versions_json.outputs.matrix) }}
        laravel: [^7.0]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_extensions: zip gd intl pcntl sodium
          command: update "laravel/framework:${{ matrix.laravel }}"

      - name: PHPUnit tests
        uses: php-actions/phpunit@v2
        with:
          php_extensions: zip gd intl pcntl sodium
          memory_limit: 2G
          bootstrap: vendor/autoload.php
          args: --no-configuration tests

      
