name: PHPUnit tests

on:
  push:
    branches:
      - github-actions

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: php-actions/composer@v5
        with:
          php_extensions: json mbstring fileinfo zip ctype dom gd iconv libxml simplexml xml xmlreader xmlwriter zlib pcre tokenizer filter pcntl pdo curl intl openssl phar

      - name: PHPUnit tests
        uses: php-actions/phpunit@v2
        with:
          bootstrap: vendor/autoload.php
          args: --no-configuration tests

      
